# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

category_types = ["Cardiology", "Pediatrics", "Radiology", "Gynaecology", "Dermatology", "Oncology", "Neurology", "Psychiatry", "Anesthesiology", "Orthopaedics"]
description = ["Cardiology is a branch of medicine that deals with the disorders of the heart as well as some parts of the circulatory system. The field includes medical diagnosis and treatment of congenital heart defects, coronary artery disease, heart failure, valvular heart disease and electrophysiology.", "Pediatrics is the branch of medicine that involves the medical care of diseases. The American Academy of Pediatrics recommends people be under pediatric care through the age of 21.", "Radiology is the medical discipline that uses medical imaging to diagnose and treat diseases within the bodies of animals, including humans.", "Gynaecology or gynecology is the medical practice dealing with the health of the female reproductive system.", "Dermatology is the branch of medicine dealing with the skin. It is a speciality with both medical and surgical aspects.", "Oncology is a branch of medicine that deals with the prevention, diagnosis, and treatment of cancer.", "Neurology is a branch of medicine dealing with disorders of the nervous system. Neurology deals with the diagnosis and treatment of all categories of conditions and disease involving the central and peripheral nervous systems, including their coverings, blood vessels, and all effector tissue, such as muscle.", "Psychiatry is the medical specialty devoted to the diagnosis, prevention, and treatment of mental disorders. These include various maladaptations related to mood, behaviour, cognition, and perceptions. See glossary of psychiatry.", "Anesthesiology, anaesthesiology, anaesthesia or anaesthetics is the medical speciality concerned with the total perioperative care of patients before, during and after surgery. It encompasses anesthesia, intensive care medicine, critical emergency medicine, and pain medicine.", "Orthopedic surgery or orthopedics, also spelled orthopaedics, is the branch of surgery concerned with conditions involving the musculoskeletal system."]

# Need to figure out how to connect arrays in 1 loop
#images = ["https://www.northcountryhospital.org/wp-content/uploads/2019/04/C-Cardiology-newport-vermont-e1554726152791.png","https://www.trinityhealth.org/wp-content/uploads/2018/05/PedsdServices.jpg","https://www.chestercountyhospital.org/-/media/images/chestercounty/major%20service%20line%20uploads/radiology/radiology%201%20main%20graphic%20720%20x%20324.ashx", "https://desunsiliguri.com/images/medical-departments/gynaecology.jpg", "https://kesseldermatology.com/wp-content/uploads/2016/02/banner-physical-1.jpg", "https://www.asco.org/sites/new-www.asco.org/files/styles/featured_tile/public/content-files/tiles_images/homepage-tile-coronavirus.png?itok=_4Un8eUo", "https://www.mcw.edu/departments/-/media/29B8655FD6E04E8496E5B660BDD7029A.ashx?anchor=middlecenter&scale=both&mode=crop", "https://www.nami.org/NAMI/media/NAMI-Media/BlogImageArchive/2019/psychiatrist-blog.jpeg", "https://thedo.osteopathic.org/wp-content/uploads/2017/10/anesthesiology-e1507232660560.jpg", "https://www.bouldermedicalcenter.com/wp-content/uploads/2014/12/Boulder-Medical-Center-Orthopedics.png"]
category_types.each do |categories|
        Specialty.create(category_title: categories, category_description: description)
    end

