# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acadeb1fda08c417a356b92a68de95c68edfaacae6be7cd164e3103e5f69b680479548f03162d46c5a7ef4f7c30bab51e1945a2b805ae09b2ddf60e29cc46980

test:
  secret_key_base: 23c2cbe555eda8b301d39ca62e95d7f75d5db1d1ff967994aed9a5cffecfcc0f40efabfe94e3535e8e0cc360ae83519460286bdd310190b79e14aecbe09ad22f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
